"""
Generate sample financial documents for testing VeritasIQ.

Creates realistic PDFs with deliberate red flags so you can test
the risk detector, financial analyzer, and compliance checker.

Run:  python generate_sample_data.py

Output:  sample_data/
  ├── acme_fy24_annual_report.pdf     (full annual report, 3 years of data)
  ├── acme_fy24_balance_sheet.pdf     (balance sheet)
  ├── acme_fy24_income_statement.pdf  (income statement)
  ├── acme_fy24_cash_flow.pdf         (cash flow statement)
  └── acme_fy24_audit_report.pdf      (audit report with going concern note)
"""

import os
import fitz  # PyMuPDF

OUTPUT_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "sample_data")

# Built-in base14 fonts (always available, extract cleanly).
# Names: helv=Helvetica, hebo=Helvetica-Bold
FONT_REGULAR = "helv"
FONT_BOLD = "hebo"


def _font_kwargs(bold=False):
    """Return font kwargs that work with insert_text/insert_textbox in PyMuPDF >=1.24."""
    return {"fontname": FONT_BOLD if bold else FONT_REGULAR}


def make_pdf(filename, title, sections, landscape=False):
    """Create a single-page-per-section PDF using a real TTF font."""
    path = os.path.join(OUTPUT_DIR, filename)
    doc = fitz.open()
    page = doc.new_page(width=842, height=595) if landscape else doc.new_page()
    rect = page.rect

    # Title
    page.insert_textbox(
        fitz.Rect(50, 30, rect.width - 50, 90),
        title,
        fontsize=18,
        align=fitz.TEXT_ALIGN_CENTER,
        **_font_kwargs(bold=True),
    )
    page.insert_text(
        fitz.Point(50, 110),
        "ACME Manufacturing Inc. | Confidential - For Testing Only",
        fontsize=9,
        **_font_kwargs(),
    )
    page.insert_text(
        fitz.Point(50, 125),
        "Generated by VeritasIQ sample data script",
        fontsize=8,
        color=(0.4, 0.4, 0.4),
        **_font_kwargs(),
    )

    for section_title, lines in sections:
        # New page per major section (keeps chunks/page mapping realistic)
        page = doc.new_page()
        rect = page.rect
        page.insert_text(
            fitz.Point(50, 40),
            title,
            fontsize=11,
            **_font_kwargs(bold=True),
        )
        page.insert_textbox(
            fitz.Rect(50, 55, rect.width - 50, 80),
            section_title,
            fontsize=14,
            color=(0.1, 0.2, 0.5),
            **_font_kwargs(bold=True),
        )
        y = 90
        for line in lines:
            if y > rect.height - 60:
                page = doc.new_page()
                rect = page.rect
                y = 50
            page.insert_text(
                fitz.Point(50, y),
                line,
                fontsize=9,
                **_font_kwargs(),
            )
            y += 16

    doc.save(path)
    doc.close()
    print(f"  created: {filename} ({os.path.getsize(path)} bytes)")
    return path


def annual_report():
    title = "ACME Manufacturing Inc. - Annual Report FY2024"
    sections = [
        ("1. Chairman's Statement", [
            "Dear Shareholders,",
            "",
            "Fiscal year 2024 was a transformative year for ACME Manufacturing. Revenue grew",
            "15.4% to $485.2 million, driven by expansion into European markets and the launch",
            "of our new automation product line.",
            "",
            "However, we must be transparent about the challenges we face. Rising input costs,",
            "supply chain disruptions, and the cost of our strategic acquisitions have increased",
            "our leverage. Management has implemented a cost reduction program targeting",
            "$40 million in annual savings.",
            "",
            "We remain confident in our long-term strategy and the strength of our product portfolio.",
        ]),
        ("2. Financial Highlights FY2024", [
            "Key Financial Metrics:",
            "",
            "Revenue: $485.2M (FY23: $420.5M, FY22: $365.1M)",
            "Gross Profit: $169.8M (FY23: $158.5M, FY22: $142.4M)",
            "Operating Income: $54.2M (FY23: $58.9M, FY22: $55.8M)",
            "Net Income: $38.7M (FY23: $42.1M, FY22: $40.3M)",
            "EBITDA: $78.5M (FY23: $74.2M, FY22: $68.9M)",
            "",
            "Ratios:",
            "Current Ratio: 1.1x (industry average: 2.0x)",
            "Debt-to-Equity: 2.1x (FY22: 1.2x)",
            "Net Profit Margin: 8.0% (FY22: 11.0%)",
            "Return on Equity: 11.2% (FY22: 16.8%)",
            "Interest Coverage: 2.4x (FY22: 5.1x)",
        ]),
        ("3. Balance Sheet Summary", [
            "Total Assets: $612.4M",
            "Cash and Cash Equivalents: $22.1M",
            "Accounts Receivable: $98.5M",
            "Inventory: $85.3M",
            "Property, Plant & Equipment: $310.2M",
            "Intangible Assets: $96.3M",
            "",
            "Total Liabilities: $418.7M",
            "Accounts Payable: $61.2M",
            "Short-term Debt: $85.0M",
            "Long-term Debt: $245.5M",
            "Total Shareholders Equity: $193.7M",
        ]),
        ("4. Income Statement FY2024", [
            "Revenue: $485,200,000",
            "Cost of Goods Sold: $315,400,000",
            "Gross Profit: $169,800,000",
            "",
            "Operating Expenses:",
            "  Selling, General & Admin: $89,600,000",
            "  Research & Development: $26,000,000",
            "Total Operating Expenses: $115,600,000",
            "",
            "Operating Income: $54,200,000",
            "Interest Expense: $18,500,000",
            "Income Before Taxes: $35,700,000",
            "Income Tax Expense: $8,900,000",
            "Net Income: $26,800,000",
            "",
            "EPS (Basic): $2.68",
            "EPS (Diluted): $2.61",
        ]),
        ("5. Cash Flow Statement FY2024", [
            "Cash Flow from Operating Activities:",
            "  Net Income: $26,800,000",
            "  Depreciation & Amortization: $24,300,000",
            "  Changes in Working Capital: ($31,500,000)",
            "  Net Cash from Operations: $19,600,000",
            "",
            "Cash Flow from Investing Activities:",
            "  Capital Expenditures: ($48,200,000)",
            "  Acquisition of Subsidiaries: ($72,000,000)",
            "  Net Cash from Investing: ($120,200,000)",
            "",
            "Cash Flow from Financing Activities:",
            "  Proceeds from Debt: $95,000,000",
            "  Dividend Payments: ($8,400,000)",
            "  Net Cash from Financing: $86,600,000",
            "",
            "Net Change in Cash: ($14,000,000)",
            "Beginning Cash Balance: $36,100,000",
            "Ending Cash Balance: $22,100,000",
        ]),
        ("6. Related Party Transactions", [
            "The Company entered into the following transactions with related parties during FY2024:",
            "",
            "1. ACME Holdings Ltd. (parent company, 51% ownership) - Management services",
            "   agreement totaling $3,200,000.",
            "",
            "2. ACME Properties LLC (owned by the CEO) - Lease payments totaling",
            "   $4,800,000 for the Company's corporate headquarters.",
            "",
            "3. Redwood Supply Co. (owned by a board member) - Raw material purchases",
            "   of $12,500,000, representing 8% of total raw material purchases.",
            "",
            "Management believes these transactions were conducted at arm's length and",
            "in the normal course of business.",
        ]),
        ("7. Subsequent Events", [
            "On June 15, 2025, subsequent to the fiscal year end, the Company received a",
            "notice from its primary lender indicating potential covenant violations related",
            "to its debt-to-EBITDA ratio.",
            "",
            "The Company is currently in discussions with the lender to negotiate a waiver.",
            "If a waiver is not obtained, the Company's $85 million short-term debt facility",
            "could become due on demand.",
        ]),
    ]
    return make_pdf("acme_fy24_annual_report.pdf", title, sections)


def balance_sheet():
    title = "ACME Manufacturing Inc. - Consolidated Balance Sheet"
    sections = [
        ("Balance Sheet (as of Dec 31)", [
            "                                     FY2024       FY2023       FY2022",
            "ASSETS",
            "Current Assets:",
            "  Cash and Cash Equivalents        22,100      36,100      28,400",
            "  Accounts Receivable               98,500      82,300      71,200",
            "  Inventory                        85,300      72,800      61,500",
            "  Prepaid Expenses                  12,400       9,800       8,100",
            "  Total Current Assets            218,300     201,000     169,200",
            "",
            "Non-Current Assets:",
            "  Property, Plant & Equipment      310,200     282,500     245,800",
            "  Intangible Assets                 96,300      58,200      42,100",
            "  Goodwill                          24,500      15,300      15,300",
            "  Total Non-Current Assets         441,000     356,000     303,200",
            "TOTAL ASSETS                       659,300     557,000     472,400",
            "",
            "LIABILITIES AND EQUITY",
            "Current Liabilities:",
            "  Accounts Payable                  61,200      52,400      43,800",
            "  Short-term Debt                   85,000      45,000      28,000",
            "  Accrued Liabilities               52,500      41,800      35,200",
            "  Total Current Liabilities        198,700     139,200     107,000",
            "",
            "Non-Current Liabilities:",
            "  Long-term Debt                    245,500     178,300     128,600",
            "  Deferred Tax Liabilities          20,600      15,800      12,400",
            "  Total Non-Current Liabilities    266,100     194,100     141,000",
            "",
            "Total Liabilities                  464,800     333,300     248,000",
            "",
            "Shareholders Equity:",
            "  Common Stock                       50,000      50,000      50,000",
            "  Retained Earnings                 144,500     173,700     174,400",
            "  Total Equity                      194,500     223,700     224,400",
            "TOTAL LIABILITIES + EQUITY         659,300     557,000     472,400",
        ]),
    ]
    return make_pdf("acme_fy24_balance_sheet.pdf", title, sections, landscape=True)


def income_statement():
    title = "ACME Manufacturing Inc. - Consolidated Income Statement"
    sections = [
        ("Income Statement (FY ending Dec 31)", [
            "                                      FY2024       FY2023       FY2022",
            "Revenue                            485,200      420,500      365,100",
            "Cost of Goods Sold                (315,400)    (262,000)    (222,700)",
            "Gross Profit                       169,800      158,500      142,400",
            "Gross Margin                         35.0%        37.7%        39.0%",
            "",
            "Operating Expenses:",
            "  Selling, General & Admin          (89,600)     (76,800)     (64,200)",
            "  Research & Development            (26,000)     (22,800)     (22,400)",
            "Total Operating Expenses           (115,600)     (99,600)     (86,600)",
            "",
            "Operating Income                     54,200       58,900       55,800",
            "Operating Margin                     11.2%        14.0%        15.3%",
            "",
            "Interest Expense                    (18,500)     (11,600)      (7,400)",
            "Other Income / (Expense)              4,500        3,200        2,800",
            "Income Before Taxes                  35,700       50,500       51,200",
            "",
            "Income Tax Expense                   (8,900)     (12,600)     (12,800)",
            "NET INCOME                           26,800       37,900       38,400",
            "Net Margin                             5.5%         9.0%        10.5%",
            "",
            "EPS (Basic)                            2.68         3.79         3.84",
            "Shares Outstanding               10,000,000   10,000,000   10,000,000",
        ]),
    ]
    return make_pdf("acme_fy24_income_statement.pdf", title, sections, landscape=True)


def cash_flow():
    title = "ACME Manufacturing Inc. - Consolidated Statement of Cash Flows"
    sections = [
        ("Cash Flow Statement (FY ending Dec 31)", [
            "                                      FY2024       FY2023       FY2022",
            "OPERATING ACTIVITIES",
            "  Net Income                        26,800       37,900       38,400",
            "  Depreciation & Amortization       24,300       20,100       17,200",
            "  Changes in Working Capital:",
            "    Accounts Receivable            (16,200)     (11,100)      (8,900)",
            "    Inventory                      (12,500)     (11,300)      (7,800)",
            "    Accounts Payable                 8,800        8,600        5,900",
            "    Accrued Liabilities             10,700        6,600        4,100",
            "  Other Adjustments                (21,500)       3,400        2,100",
            "NET CASH FROM OPERATIONS            19,600       54,200       51,000",
            "",
            "INVESTING ACTIVITIES",
            "  Capital Expenditures             (48,200)     (36,700)     (30,200)",
            "  Acquisition of Subsidiaries      (72,000)      (5,000)          0",
            "  Purchase of Intangibles          (38,100)     (16,100)     (11,200)",
            "  Other Investing                     2,100        1,800       (3,400)",
            "NET CASH FROM INVESTING           (156,200)     (56,000)     (44,800)",
            "",
            "FINANCING ACTIVITIES",
            "  Proceeds from Long-term Debt      95,000       49,700       20,300",
            "  Repayment of Short-term Debt      (7,600)      (3,100)      (2,500)",
            "  Dividend Payments                 (8,400)      (9,600)      (9,400)",
            "  Other Financing                   (3,900)       1,100       (2,900)",
            "NET CASH FROM FINANCING             75,100       38,100        5,500",
            "",
            "NET CHANGE IN CASH                (61,500)       36,300       11,700",
            "Cash, beginning of year              83,600       47,300       35,600",
            "Cash, end of year                    22,100       83,600       47,300",
        ]),
    ]
    return make_pdf("acme_fy24_cash_flow.pdf", title, sections, landscape=True)


def audit_report():
    title = "ACME Manufacturing Inc. - Independent Auditor's Report"
    sections = [
        ("Independent Auditor's Report", [
            "To the Shareholders and Board of Directors of ACME Manufacturing Inc.",
            "",
            "Opinion",
            "",
            "We have audited the consolidated financial statements of ACME Manufacturing Inc.",
            "which comprise the consolidated balance sheet as at December 31, 2024, and the",
            "consolidated statement of income, consolidated statement of changes in equity,",
            "and consolidated statement of cash flows for the year then ended, and notes to",
            "the financial statements.",
            "",
            "In our opinion, except for the effects of the matter described in the Basis for",
            "Qualified Opinion section, the consolidated financial statements present fairly,",
            "in all material respects, the financial position of the Company.",
            "",
            "Basis for Qualified Opinion",
            "",
            "As described in Note 6 to the financial statements, the Company entered into",
            "lease agreements with ACME Properties LLC, an entity controlled by the Chief",
            "Executive Officer. The Company recorded lease payments of $4.8 million to this",
            "related party during the year. The terms of these agreements were not subject",
            "to independent valuation, and we were unable to determine whether the lease",
            "payments were made at arm's length.",
        ]),
        ("Key Audit Matters", [
            "Revenue Recognition",
            "",
            "The Company recognized revenue of $485.2 million in FY2024. The timing of revenue",
            "recognition is a key audit matter due to the complexity of the Company's",
            "multi-element software and hardware arrangements.",
            "",
            "We performed procedures including testing a sample of revenue transactions,",
            "reviewing the Company's revenue recognition policies against ASC 606, and",
            "obtaining management representations.",
            "",
            "Valuation of Intangible Assets",
            "",
            "The Company acquired two subsidiaries during FY2024 for total consideration of",
            "$72 million, recording $38.1 million of intangible assets. Valuation of these",
            "intangibles involved significant estimates including discount rates and",
            "projected cash flows.",
        ]),
        ("Going Concern Note", [
            "Substantial Doubt About the Company's Ability to Continue as a Going Concern",
            "",
            "The accompanying consolidated financial statements have been prepared assuming",
            "the Company will continue as a going concern.",
            "",
            "As discussed in Note 2.1 to the financial statements, the Company's operating",
            "cash flows have declined from $51.0 million in FY2022 to $19.6 million in FY2024.",
            "The Company's current ratio of 1.1x is below the industry average of 2.0x, and",
            "its debt-to-equity ratio has risen to 2.1x.",
            "",
            "Additionally, on June 15, 2025, subsequent to year-end, the Company received",
            "notice of potential covenant violations from its primary lender. These matters,",
            "along with the fact that $85 million of short-term debt matures within 12 months",
            "while the Company has only $22.1 million in cash, raise substantial doubt about",
            "the Company's ability to continue as a going concern.",
            "",
            "The financial statements do not include any adjustments that might result from",
            "the outcome of this uncertainty.",
        ]),
        ("Critical Accounting Estimates", [
            "Inventory Valuation",
            "",
            "The Company maintains inventory of $85.3 million. Due to the rapid technological",
            "obsolescence in the Company's product lines, the Company recorded an inventory",
            "write-down of $6.2 million in FY2024. The determination of net realizable value",
            "involves significant management judgment.",
            "",
            "Allowance for Doubtful Accounts",
            "",
            "Accounts receivable balance of $98.5 million. The Company's allowance for",
            "doubtful accounts was reduced from 3.2% in FY2023 to 2.1% in FY2024 despite an",
            "increase in accounts receivable aging over 90 days from 8% to 14% of the balance.",
        ]),
    ]
    return make_pdf("acme_fy24_audit_report.pdf", title, sections)


def run_all():
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    print(f"Generating sample documents in: {OUTPUT_DIR}\n")
    annual_report()
    balance_sheet()
    income_statement()
    cash_flow()
    audit_report()
    print("\nDone. 5 documents generated.")
    print("\nTest flow:")
    print("  1. Upload each PDF via POST /api/v1/documents/upload")
    print("  2. Process each via POST /api/v1/documents/{id}/process")
    print("  3. Query via POST /api/v1/analysis/query")
    print("  4. Generate report via POST /api/v1/reports")


if __name__ == "__main__":
    run_all()
